#!/bin/bash

#watch -n 1 "echo '`date "+%Y%m%d%t%T%t"`'; ps -ax -o pid,vsz,rss,min_flt,maj_flt,time,cmd | grep -v grep | grep caffe >> logs"
prefix=$1
path=~/logs/
mkdir -p $path

#echo #pid,vsz,rss,min_flt,maj_flt,time,cmd >> $path/caffe-log

timestamp=$(date "+%Y%m%d%t%T%t")
ps=$(ps -ax -o pid,vsz,rss,min_flt,maj_flt,time,cmd | grep -v "grep\|stats\|time" | grep caffe)
echo $timestamp$ps >> $path$prefix-caffe-ps

