#!/bin/bash

caffe_root=~/caffe/
model_base="_alexnet"
model=$1

path_root=~/logs/
timestamp=$(date +%Y%m%d%H%M%S)

path=$path_root$timestamp/
name=$model$model_base

mkdir -p $path

bash -c "while true; do ./caffe-stats $path $name; sleep 1; done" &
./nvidia-stats $path $name &	
nvp=$!

cd $caffe_root
nvprof --export-profile $path$name.nvprof /usr/bin/time -v -o $path$name-time build/tools/caffe train --solver=models/$model$model_base/solver.prototxt --gpu 1 2>&1 | tee $path$name-caffe.log
cd -

kill $nvp
pkill -P $$
